# Read in the file
with open('1.txt', 'r') as file :
  filedata = file.read()

# Replace the target string

filedata = filedata.replace(',','36,')
filedata = filedata.replace('a','1,')
filedata = filedata.replace('b','2,')
filedata = filedata.replace('c','3,')
filedata = filedata.replace('d','4,')
filedata = filedata.replace('e','5,')
filedata = filedata.replace('f','6,')
filedata = filedata.replace('g','7,')
filedata = filedata.replace('h','8,')
filedata = filedata.replace('i','9,')
filedata = filedata.replace('j','10,')
filedata = filedata.replace('k','11,')
filedata = filedata.replace('l','12,')
filedata = filedata.replace('m','13,')
filedata = filedata.replace('n','14,')
filedata = filedata.replace('o','15,')
filedata = filedata.replace('p','16,')
filedata = filedata.replace('q','17,')
filedata = filedata.replace('r','18,')
filedata = filedata.replace('s','19,')
filedata = filedata.replace('t','20,')
filedata = filedata.replace('u','21,')
filedata = filedata.replace('v','22,')
filedata = filedata.replace('w','23,')
filedata = filedata.replace('x','24,')
filedata = filedata.replace('y','25,')
filedata = filedata.replace('z','26,')
filedata = filedata.replace('.','27,')
filedata = filedata.replace('!','28,')
filedata = filedata.replace('?','29,')
filedata = filedata.replace(' ','30,')
filedata = filedata.replace(';','31,')
filedata = filedata.replace(':','32,')
filedata = filedata.replace('-','33,')
filedata = filedata.replace('"','34,')
filedata = filedata.replace('\n','35,')

filedata = filedata.replace('A','1,')
filedata = filedata.replace('B','2,')
filedata = filedata.replace('C','3,')
filedata = filedata.replace('D','4,')
filedata = filedata.replace('E','5,')
filedata = filedata.replace('F','6,')
filedata = filedata.replace('G','7,')
filedata = filedata.replace('H','8,')
filedata = filedata.replace('I','9,')
filedata = filedata.replace('J','10,')
filedata = filedata.replace('K','11,')
filedata = filedata.replace('L','12,')
filedata = filedata.replace('M','13,')
filedata = filedata.replace('N','14,')
filedata = filedata.replace('O','15,')
filedata = filedata.replace('P','16,')
filedata = filedata.replace('Q','17,')
filedata = filedata.replace('R','18,')
filedata = filedata.replace('S','19,')
filedata = filedata.replace('T','20,')
filedata = filedata.replace('U','21,')
filedata = filedata.replace('V','22,')
filedata = filedata.replace('W','23,')
filedata = filedata.replace('X','24,')
filedata = filedata.replace('Y','25,')
filedata = filedata.replace('Z','26,')

# Write the file out again
with open('1.txt', 'w') as file:
  file.write(filedata)
